import smtplib
from socket import error


host = 'smtp.mailtrap.io'
login = 'login'  # paste your login generated by Mailtrap
password = 'password'  # paste your password generated by Mailtrap


class Message(object):
    """Add description."""
    sender = None
    receiver = None

    def __init__(self, sender=None, receiver=None, message=None):
        """Specify the sender's and receiver's email addresses."""
        self.sender = sender if sender else 'Private Person <from@{}>'.format(host)
        self.receiver = receiver if receiver else 'A Test User <to@{}>'.format(host)
        self.message = message

    @property
    def message(self):
        """Get message property."""
        return self.__message

    @message.setter
    def message(self, msg=None):
        """Set message property."""
        if not msg:
            self.__message = """\
            Subject: Hi Mailtrap
            To: {receiver}
            From: {sender}
            This is a test e-mail message.""".format(receiver=self.receiver, sender=self.sender)
        else:
            self.__message = msg


class SendEmail(object):
    """Service to run emails."""
    port = 2525
    smtp_server = host

    def __init__(self, login_, password_):
        # type: (Optional[str], Optional[str]) -> None
        # paste your login and password generated by Mailtrap
        if login_ and password_:
            self.auth = (login_, password_)
        else:
            self.auth = (login, password)

    def run(self, m):
        # type: (Message) -> None
        try:
            # Send your message with credentials specified above
            server = smtplib.SMTP(self.smtp_server, self.port)
            server.login(*self.auth)
            server.sendmail(m.sender, m.receiver, m.message)
            server.quit()
        except error:
            # tell the script to report if your message was sent or which
            # errors need to be fixed
            print('Failed to connect to the server. Bad connection settings?')
        except smtplib.SMTPAuthenticationError:
            print('Failed to connect to the server. Wrong user/password?')
        except smtplib.SMTPException, e:
            print('SMTP error occurred: {}'.format(str(e)))
        else:
            print('Sent')


if __name__ == "__main__":
    message = Message()
    SendEmail(*("11113d506b95d4", "079598811116b1")).run(Message())
