# The first step is always the same: import all necessary components:

import smtplib
from socket import gaierror
from typing import Optional

host = 'smtp.mailtrap.io'
login = 'login'  # paste your login generated by Mailtrap
password = 'password'  # paste your password generated by Mailtrap


class Message:
    """Add description."""
    sender = None
    receiver = None

    def __init__(self, sender=None, receiver=None, message=None):
        """Specify the sender's and receiver's email addresses."""
        self.sender = sender if sender else f'Private Person <from@{host}>'
        self.receiver = receiver if receiver else f'A Test User <to@{host}>'
        self.message = message

    @property
    def message(self):
        """Get message property."""
        return self.__message

    @message.setter
    def message(self, msg=None):
        """Set message property."""
        if not msg:
            self.__message = f"""\
            Subject: Hi Mailtrap
            To: {self.receiver}
            From: {self.sender}
            This is a test e-mail message."""
        else:
            self.__message = msg


class SendEmail:
    """Service to run emails."""
    port = 2525
    smtp_server = host

    def __init__(self, login_: Optional[str], password_: Optional[str]) -> None:
        # paste your login and password generated by Mailtrap
        if login_ and password_:
            self.auth = (login_, password_)
        else:
            self.auth = (login, password)

    def run(self, m: Message) -> None:
        try:
            # Send your message with credentials specified above
            with smtplib.SMTP(self.smtp_server, self.port) as server:
                server.login(*self.auth)
                server.sendmail(m.sender, m.receiver, m.message)
        except (gaierror, ConnectionRefusedError):
            # tell the script to report if your message was sent or which
            # errors need to be fixed
            print('Failed to connect to the server. Bad connection settings?')
        except smtplib.SMTPServerDisconnected:
            print('Failed to connect to the server. Wrong user/password?')
        except smtplib.SMTPException as e:
            print(f'SMTP error occurred: {str(e)}')
        else:
            print('Sent')


if __name__ == "__main__":
    import pdb; pdb.set_trace()
    SendEmail(*("11113d506b95d4", "079598811116b1")).run(Message())
